apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

# ConfigMaps for Grafana dashboards
configMapGenerator:
  - name: grafana-dashboard-cluster-resources
    files:
      - dashboards/cluster/k8s_resource_usage_cluster.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-coredns
    files:
      - dashboards/cluster/coredns-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-etcd
    files:
      - dashboards/cluster/etcd-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-apiserver
    files:
      - dashboards/cluster/apiserver-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-certificates
    files:
      - dashboards/cluster/certificate-expiration.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-namespace
    files:
      - dashboards/namespace/k8s_resource_usage_namespace.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-pods
    files:
      - dashboards/pods/k8s_resource_usage_namespace_pods.json
    options:
      labels:
        grafana_dashboard: "1"

labels:
  - pairs:
      app.kubernetes.io/name: grafana-dashboards
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/part-of: kubernetes-monitoring
